source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/anonymous-qsh/LQTableViewManager.git'

platform :ios, '7.0'

target "RETableViewManagerExample" do
  pod 'LQTableViewManager', :path => '../'
end
