source 'https://github.com/CocoaPods/Specs.git'

source 'https://github.com/anonymous-qsh/Specs.git'

platform :ios, '8.0'

target "RETableViewManagerExample" do
  pod 'LQUIColor'
  pod 'LQTableViewManager', :path => '../'
end
